# Generated by Django 5.0.6 on 2024-05-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=150, null=True)),
                ('isPasswordReset', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('preferredLanguage', models.CharField(default='en', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('phone', models.CharField(default='', max_length=100)),
                ('profileImageKey', models.CharField(max_length=255, null=True)),
                ('profileImageUrl', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
